version: 2.1
jobs:
  build:
    docker:
      - image: docker:18-git
    working_directory: ~/final_analisis
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Crear imagen de docker
          command: |
            echo 'Se inicia la compilacion'
            ls
            docker login -u $docker_usr -p $docker_pass
            docker build -t allyogi/final_analisis:latest .
            docker push allyogi/final_analisis:latest
            echo 'Se inicia la compilacion'
  deploy:
    docker:
      - image: alpine
    steps:
      - run:
          name: Despliegue
          command: |
            apk update
            apk add openssh
            apk add sshpass
            sshpass -p $SRV_PASS ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $SRV_USR@$SRV_IP 'docker pull allyogi/final_analisis:latest; docker stop final_analisis; docker rm final_analisis; docker run -d -p 80:80 --name final_analisis allyogi/final_analisis:latest; exit'
            echo 'Despliegue exitoso'
workflows:
    flujo:
      jobs:
        - build
        - deploy:
            requires:
              - build